### ISSUE TITLE
ionic view on iOS v1.0.6 doesn't keep localStorage

### ISSUE THREAD

**Issue by lifecube** [ionic-team/ionic-view-issues#117]
we deploy the same app running on ionic view.
Data can be kept in localStorage on android ionic view.
But it cannot be kept on iOS.

Similar issue is reported to [here](http://forum.ionicframework.com/t/ionic-view-1-0-6-no-localstorage/25196)

**Comment by simplesmiler** [comment]
Having the same issue.
Application inside View always starts with an empty localStorage (except for the View own keys).

**Comment by tlancina** [comment]
Hey this is intentional, as apps had access to View's and other apps' localStorage which was causing issues. As a fix, we made it so localStorage is cleared after each use, but getting localStorage to persist on a per app basis is probably doable and will be added in the future (since it sounds like clearing localStorage causes just as many issues!).

**Comment by brihogan** [comment]
Would love to be able to use localStorage. My app is just about unusable without it. :( But, overall the app is freakin' awesome! Thanks!!!

**Comment by beebase** [comment]
+1 for localStorage. For the rest...ionic view = very cool.

**Comment by volantes** [comment]
+1 for localStorage.

Thanks for the great service and services Ionic Team. 

You guys really are awesome.

**Comment by patrickmcd** [comment]
Yep, looking for this too.

**Comment by felipepastor** [comment]
Any updates about localstorage for ios? Thx

**Comment by simplesmiler** [comment]
Want this badly.

**Comment by mesca** [comment]
+1

**Comment by wgrafael** [comment]
+1

**Comment by ArjenB** [comment]
+1. Is a new version in the works?

**Comment by ArjenB** [comment]
Since ionic view is an ionic app, adding this functionality should be easy (prepend the user-id to the local storage for example). For testing on iOS devices having persistent local storage is a must for me. Is there any way to get this issue higher priority. I'd be happy to implement the change.

**Comment by JLNNN** [comment]
+1

**Comment by rrubio** [comment]
+1

**Comment by danielnbarros** [comment]
+1

**Comment by cybertim** [comment]
+1

**Comment by ericodom** [comment]
yeah...gotta have it

**Comment by dadria** [comment]
+1

**Comment by comalpine** [comment]
+1

**Comment by simonefalcini** [comment]
+1

**Comment by leouofa** [comment]
+1

**Comment by seven-ply** [comment]
+1

**Comment by Swahjak** [comment]
+1

**Comment by sulram** [comment]
+1 !!!

**Comment by jimcamut** [comment]
+2

**Comment by azzy** [comment]
+1 @tlancina any update on this? Is there anything we can do to help make this happen?

**Comment by sulram** [comment]
on Android, sometime it keeps, sometimes not

**Comment by jzaric** [comment]
+1 Is there an ETA for this? Also, let us know if we can help.

**Comment by reneklootwijk** [comment]
+1

**Comment by domhnallw** [comment]
I'd taken it for granted that localStorage would be persistent, this is quite a surprise and a disappointment. Looks like I'll have to come up with a plan B pretty quick.

Please implement this feature.

**Comment by AdrienDC** [comment]
+1

**Comment by digows** [comment]
+1

**Comment by JustinTrainor** [comment]
+1

**Comment by loolooii** [comment]
I don't see how this could conflict with other apps. Just use a unique combination of for example ionic username and app name or whatever.

**Comment by mattmccray** [comment]
Well, this has been open for over a year now. Clearly it's not a priority -- Can anyone suggest a work-around, or another way to persist some data in Ionic View for iOS?

**Comment by domhnallw** [comment]
At the risk of speaking out of turn, I do seem to recall having a conversation with one of the Ionic guys some time back in Slack, and was informally told that this wasn't really what Ionic View was for - the impression I get now is that it's really more of a UI design testbed. The show-stopper for me was that AJAX requests didn't work - at all - inside Ionic View, and I only found that out at a very advanced stage.

I thought you could design app prototypes and deploy them for evaluation, but there are a bunch of things that Ionic View can't do, and I suspect this is completely intentionally. Not out of any malice or anything like that, but so that the various App Stores will accept it, because - the more I think of it - what I wanted it to do would constitute a near-complete end run around all of the checks and balances in place in those app stores and allow you to basically deploy whatever you liked, as long as it "fit" inside a hybrid app. I couldn't imagine Apple, for example, being okay with this.

(Disclaimer: This information is several months old, so stuff may have changed in the interim)

**Comment by Swahjak** [comment]
@domhnallw This is actually not true. I have had an app for quite a while in ionic-view and it functions 'ok'. Ajax and storage. I do however agree with the point that Ionic View is mostly a 'preview' window and not fit to actually be used as a fully functional app platform.

To elaborate:

* Storage is possible using SQLite (http://ngcordova.com/docs/plugins/sqlite/). In my opinion it's not that well documented and there are some issues when using it in Ionic View, but I did get it to work.
* I've never experienced any problems using ajax calls, and the app has been around for at least 6 months.

That being said, it took me quite a while to get it al functioning. And different platforms (ios, android) and even version (marshmallow, lollipop) perform differently.

**Comment by domhnallw** [comment]
@Swahjak thanks for the clarification - guess I mustn't have looked hard enough. I remember I was getting no joy, but perhaps I was doing something wrong...

**Comment by simplesmiler** [comment]
Cookies appear to be a workaround on iOS.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
