### ISSUE TITLE
upload seems to be modifying my index.html causing the app to go blank after ionic serve

### ISSUE THREAD

**Issue by shiva2492** [ionic-team/ionic-view-issues#141]
after I run ionic upload ,the index.html file gets modified automatically and the tag (ion-nav-view) is gone from it where the content from templates was rendered in and am stuck with a blank screen app on ionic view app.
Don't know what to do even tried to disable automatic code modification by using this command in project repo( ionic config set disable_modifications true).
Kindly help if anyone has gone through the same issue or solved one like this.

**Comment by qmarcos** [comment]
Hi shiva, 

I'm pretty sure your problem is related to this issue on the ionic-cli and ionic-app-lib projects: https://github.com/driftyco/ionic-cli/issues/452#issuecomment-224955052 

I'm really surprised this issue is still not solved because there are a lot of scenarios where you can not use ionic view because of it.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
