### ISSUE TITLE
Status Bar hidden but still showing persistent background

### ISSUE THREAD

**Issue by jackanderson** [ionic-team/ionic-view-issues#210]
<img width="352" alt="screen shot 2017-03-05 at 11 46 21 pm" src="https://cloud.githubusercontent.com/assets/316927/23600977/0d58148e-01fe-11e7-8213-6314352730c8.png">

I have installed the cordova plugin and have the following occur at runtime. 
The white box still appears when switched into landscape mode and back. I am using the iOS version of ionicview and am running iOS version 10 on an iphone 6s. Ive tried many different things and still the background of the status bar still persists.
```

 $ionicPlatform.ready(function() {
    ionic.Platform.fullScreen(true,false);  
    if (window.StatusBar) {
        StatusBar.hide();
    }
}
```

**Comment by tylermakin** [comment]
I am also experiencing this issue. The issue only appears when using the Ionic View app and does not appear when building and testing an app (e.g. in Xcode).

This blank bar appears to use the (Ionic v2+) translucent style and appears regardless of which [style](https://ionicframework.com/docs/native/status-bar/#styleDefault) is set with the Status Bar plugin

The issue is further documented on the Ionic forum [here](https://forum.ionicframework.com/t/how-to-hide-bar-behind-status-bar/88270).

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
