### ISSUE TITLE
Not updating new app since CLI V3

### ISSUE THREAD

**Issue by alexbainbridge** [ionic-team/ionic-view-issues#225]
I know when we do ionic upload that intermittently if you go to ionic view you would not get the latest version of the app.

However since v3 it has moved to 100% of the time.....

There is a discussion about this on https://forum.ionicframework.com/t/ionic-upload/96063/3 which appears to suggest that this is being experienced by a wide number of people (more so than the intermittent issue previously)

Wonder if Ionic team could write the code a bit more defensively. Could the Ionic View code catch these situations a bit more?

Thanks!

**Comment by scottmotion** [comment]
I'd just like to throw my hat in the ring by saying that i've experienced some problems with the update process. Particularly when ppl want to view my app I always have to remind them to "clear app data" so that they will have the latest version. Why not just force this or provide an "always update" setting? Also when these other users are running an old version of my app they create unexpected data in my database, as i've changed the structure since they last updated.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
