### ISSUE TITLE
download or update app gives "sync failed status 200"

### ISSUE THREAD

**Issue by mnewmedia** [ionic-team/ionic-view-issues#90]
Hi I ever get the message "sync failed status 200". I tried do delete app, update app, created a new app-id nothing helped on my ios. 

does somebody know why?

**Comment by sawo** [comment]
I had similar issues. My theory is that if you let your mobile to lock the screen (, because the sync process takes too much time), then ionic cannot sync properly. What i did last  is tapped the screen regularly to interrupt the idle time of the phone. This way the ionic was able to do the sync correctly. I still need to test this theory, but i thing this is the way to avoid the issue. Probably i is an ionic view bug that cannot sync properly in background.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
